#name: Build Vue
#on: [push]
#jobs:
#  build_vue:
#    runs-on: ubuntu-latest
#    name: Build Vue
#    steps:
#    - uses: actions/checkout@v2
#    - id: Build-Vue
#      uses: xRealNeon/VuePagesAction@1.0.1
#      with:
#        username: 'atugangui'
#        reponame: 'amandatugangui'
#        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
#        VUE_APP_USER_ID: ${{ secrets.USER_ID }}
#  sitemap_job:
#    runs-on: ubuntu-latest
#    name: Generate a sitemap
#
#    steps:
#    - name: Checkout the repo
#      uses: actions/checkout@v2
#      with:
#        fetch-depth: 0 
#
#    - name: Generate the sitemap
#      id: sitemap
#      uses: cicirello/generate-sitemap@v1
#      with:
#        base-url-path: https://amandatugangui.com/
#
#    - name: Output stats
#      run: |
#        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
#        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
#        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
#
#    - name: Create Pull Request
#      uses: peter-evans/create-pull-request@v3
#      with:
#        title: "Automated sitemap update"
#        body: > 
#          Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
#          GitHub action. Automated pull-request generated by the 
#          [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
#        author: Amanda Tugangui
#        committer: Amanda Tugangui
#        branch: create-pull-request/sitemap
#        delete-branch: true
#

