name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'atugangui'
        reponame: 'amandatugangui'
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        VUE_APP_SERVICE_ID: ${{ secrets.SERVICE_ID }}
        VUE_APP_TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
        VUE_APP_USER_ID: ${{ secrets.USER_ID }}
    name: generate-sitemap
    uses: cicirello/generate-sitemap@v1.8.3

